import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/contexts/AuthContext";
import { toast } from "sonner";

export interface QuizQuestion {
  id?: string;
  question_text: string;
  question_type: "mcq" | "true_false" | "open";
  options_json?: { key: string; text: string }[] | null;
  answer?: string | null;
  points: number;
  sort_order: number;
}

export interface Quiz {
  id: string;
  teacher_id: string;
  class_id: string | null;
  subject_id: string | null;
  title: string;
  title_ar: string | null;
  lesson_ref: string | null;
  book_id: string | null;
  due_date: string | null;
  assigned: boolean;
  created_at: string;
}

/** Fetch all quizzes belonging to the current teacher. */
export function useMyQuizzes() {
  const { user } = useAuth();
  return useQuery({
    queryKey: ["my_quizzes", user?.id],
    queryFn: async (): Promise<Quiz[]> => {
      if (!user) return [];
      const { data, error } = await (supabase as any)
        .from("quizzes")
        .select("*")
        .eq("teacher_id", user.id)
        .order("created_at", { ascending: false });
      if (error) throw error;
      return data || [];
    },
    enabled: !!user,
  });
}

/** Fetch questions for a specific quiz.
 * Students should pass ``includeAnswerKey: false`` until the quiz is submitted so the key is not selected from the DB. */
export function useQuizQuestions(
  quizId: string | null,
  opts?: { includeAnswerKey?: boolean },
) {
  const includeAnswerKey = opts?.includeAnswerKey !== false;
  return useQuery({
    queryKey: ["quiz_questions", quizId, includeAnswerKey ? "with_key" : "stem_only"],
    queryFn: async (): Promise<QuizQuestion[]> => {
      if (!quizId) return [];
      const columns =
        "id, quiz_id, question_text, question_type, options_json, points, sort_order, created_at";
      const selectCols = includeAnswerKey ? `${columns}, answer` : columns;
      const { data, error } = await (supabase as any)
        .from("quiz_questions")
        .select(selectCols)
        .eq("quiz_id", quizId)
        .order("sort_order");
      if (error) throw error;
      return data || [];
    },
    enabled: !!quizId,
  });
}

/** Normalize Eastern-Arabic / Persian digits to Western (splitting relies on latin digits sometimes). */
function westernizeNumerals(input: string): string {
  return input
    .replace(/[\u0660-\u0669]/g, (c) => String(c.charCodeAt(0) - 0x0660))
    .replace(/[\u06F0-\u06F9]/g, (c) => String(c.charCodeAt(0) - 0x06f0));
}

function isQuestionFirstLine(raw: string): boolean {
  const z = raw.trim();
  if (!z || /^#{1,6}\s+\S/u.test(z)) return false;
  // 1. ... / 12) ...
  if (/^\d+\s*[.):؛,\-‑–]\s+\S/u.test(z)) return true;
  // السؤال 3: أو السؤال 3.
  if (/^(?:السؤال|سؤال)\s*\d+\s*[.:);،\-‑–]?\s+\S/ui.test(z)) return true;
  if (/^[Qq]\s*\d+\s*[.):؛]\s+\S/u.test(z)) return true;
  return false;
}

/** Drop intro lines (# titles, blanks) until first numbered question appears. */
function trimLinesBeforeFirstQuestion(lines: string[]): string[] {
  const idx = lines.findIndex(isQuestionFirstLine);
  if (idx < 0) return lines.filter((ln) => ln.trim().length > 0 || ln.includes("\u200f"));
  return lines.slice(idx);
}

function stripStemNumberLine(line: string): string {
  return line
    .trim()
    .replace(/^(?:السؤال|سؤال)\s*\d+\s*[.:);،\-‑–]?\s*/i, "")
    .replace(/^[Qq]\s*\d+\s*[.):؛]\s+/, "")
    .replace(/^\d+\s*[.):؛,\-‑–]\s+/, "")
    .replace(/^#\s*/, "")
    .trim();
}

function looksLikeOption(line: string): boolean {
  const x = line.trim();
  return (
    /^\(?\s*[أبتجدةABCDEFGHabcd]\s*[.):؛,\-‑–]\s*\S+/u.test(x) || /^[-‧•‧·]\s*\S+/u.test(x)
  );
}

/** Parse the raw questions_text string generated by the AI into QuizQuestion array. */
export function parseQuestionsFromText(text: string, retryDepth = 0): QuizQuestion[] {
  if (!text?.trim()) return [];

  let normalized = westernizeNumerals(text.replace(/\r\n/g, "\n").replace(/\r/g, "\n"));
  /** Collapse BOM */
  normalized = normalized.replace(/^\uFEFF/, "");

  let linesAll = normalized.split("\n").map((l) => l.trimEnd());
  linesAll = trimLinesBeforeFirstQuestion(linesAll);

  /** Slice into blocks: each begins at a numbered / السؤال N line */

  const blocks: string[][] = [];

  let cur: string[] = [];

  for (const ln of linesAll) {
    const trimmedLine = ln.trim();
    const isEmpty = trimmedLine === "";

    if (isEmpty && cur.length) {
      /** keep intra-question blanks as soft break optional */
      cur.push("");
      continue;
    }
    if (isEmpty && !cur.length) continue;

    if (isQuestionFirstLine(ln) && cur.length) {
      blocks.push(cur);
      cur = [ln];
      continue;
    }

    /** First block may start mid-file */
    cur.push(ln);
  }

  if (cur.length) blocks.push(cur);

  const questions: QuizQuestion[] = [];

  blocks.forEach((blockLinesRaw) => {
    /** prune leading empties inside block */
    while (blockLinesRaw.length && !blockLinesRaw[0]?.trim()) blockLinesRaw.shift();
    while (blockLinesRaw.length && !blockLinesRaw[blockLinesRaw.length - 1]?.trim()) blockLinesRaw.pop();
    /** drop markdown heading if model embedded one */
    while (blockLinesRaw.length && /^#{1,6}\s+\S/u.test(blockLinesRaw[0].trim())) blockLinesRaw.shift();
    if (!blockLinesRaw.length) return;

    const stemPrimary = stripStemNumberLine(blockLinesRaw[0]);
    /** If strip cleared line, try next raw line briefly */
    const stem =
      stemPrimary ||
      (blockLinesRaw.length > 1 ? stripStemNumberLine(blockLinesRaw.slice(1).find((x) => x.trim()) ?? "") : "");
    if (!stem || stem.length < 3) return;

    const tail = blockLinesRaw.slice(1);

    let cleanedTail = [...tail];
    while (cleanedTail.length && !cleanedTail[0].trim()) cleanedTail.shift();

    /** Find answer row */
    const ansIdx = cleanedTail.findIndex((l) =>
      /^\s*(?:الإجابة|المفتاح|الصحيح|Answer|Correct)\s*[:\s]/iu.test(l.trim()),
    );
    let beforeAns = cleanedTail.slice(0, ansIdx >= 0 ? ansIdx : cleanedTail.length);
    let answer: string | null =
      ansIdx >= 0
        ? cleanedTail[ansIdx]
            .trim()
            .replace(/^\s*(?:الإجابة|المفتاح|الصحيح|Answer|Correct)\s*[:\s]*/iu, "")
            .trim()
        : null;

    /** If answer line absent, lines may embed الإجابة inline */
    if (!answer) {
      const inline = [...beforeAns].reverse().find((l) =>
        /(?:الإجابة|Answer)\s*[:\s]/iu.test(l.trim()),
      );
      if (inline) {
        const m = inline.match(/(?:الإجابة|Answer)\s*[:\s]\s*(.+)/iu);
        if (m?.[1]) answer = m[1].trim();
      }
    }

    /** Second pass: rebuild beforeAns excluding lines that ARE only answer */
    beforeAns = beforeAns.filter((l) => !/^\s*(?:الإجابة|المفتاح|Answer|Correct)\s*[:\s]/iu.test(l.trim()));

    /** Re-scan options after stripping answer echoes */
    const optionLines = beforeAns.filter(looksLikeOption);
    /** Non-option explanatory lines appended to stem (rare paragraph between stem and opts) */

    let qType: "mcq" | "true_false" | "open" = "open";
    let options: { key: string; text: string }[] | null = null;

    if (optionLines.length >= 2) {
      qType = "mcq";
      const keys = ["A", "B", "C", "D", "E", "F"];
      options = optionLines.slice(0, keys.length).map((l, i) => ({
        key: keys[i],
        text: l
          .trim()
          .replace(/^\(?\s*[أبتجدةABCDEFGHabcd]\s*[.):؛,\-‑–]\s+/u, "")
          .replace(/^[-‧•]\s+/, "")
          .trim(),
      }));

      /** Map Arabic answer hints (إجابة: أ…) to Latin keys stored in DB */

      if (answer) {
        const raw = answer.replace(/\([^)]*\)/g, "").trim();
        const token = raw.split(/[\s.،؛]+/).find(Boolean) ?? raw;
        const ch = [...token.trim()][0] ?? "";

        const map: Record<string, string> = {
          أ: "A",
          إ: "A",
          آ: "A",
          ا: "A",
          ب: "B",
          ج: "C",
          ت: "C",
          ث: "C",
          د: "D",
        };
        if (ch && map[ch]) answer = map[ch];
      }
    } else if (/صواب|خطأ|\btrue\b|\bfalse\b/i.test(`${stem}\n${beforeAns.join("\n")}`)) {
      qType = "true_false";
      /** Normalize stored answer keywords for Arabic UI matching */
      if (answer && /خطأ|false/i.test(answer)) answer = answer.match(/خطأ|false/i)?.[0] === "false" ? "false" : "خطأ";
      else if (answer && /صواب|true/i.test(answer))
        answer = answer.match(/^true$/i) ? "true" : answer.includes("صواب") ? "صواب" : answer;
    }

    /** Junk filter: headings accidentally parsed as lone question */

    if (
      (/^(اختبار|تقييم|الوحدة|وحدة|درس\b)/iu.test(stem) && stem.length < 140 && (!options || options.length < 2)) &&
      beforeAns.every((ln) => !looksLikeOption(ln))
    ) {
      return;
    }

    questions.push({
      question_text: stem,
      question_type: qType,
      options_json: options,
      answer,
      points: 1,
      sort_order: questions.length,
    });
  });

  if (!questions.length) {
    const alt =
      normalized
        .replace(/\u200f|\u200e/g, "")
        .split(/\n\s*(?=\d+\s*[.):؛,\-‑–]\s+\S)/gu)
        .map((b) => b.trim())
        .filter((b) => b.length > 12) ?? [];
    if (alt.length > 1 && retryDepth < 4) {
      return parseQuestionsFromText(alt.join("\n\n"), retryDepth + 1);
    }

    let single = normalized.trim();

    /** Strip leading hashes for student's single open-Q fallback readability */

    single = single.replace(/^#{1,6}\s+/m, "");

    return [{ question_text: single, question_type: "open", points: 1, sort_order: 0 }];
  }

  return questions.map((q, i) => ({ ...q, sort_order: i }));
}

interface SaveQuizPayload {
  title: string;
  title_ar?: string;
  lesson_ref?: string;
  book_id?: string;
  subject_id?: string;
  questions: QuizQuestion[];
}

/** Insert a new quiz + questions. Returns the created quiz id. */
export function useSaveQuiz() {
  const { user } = useAuth();
  const qc = useQueryClient();

  return useMutation({
    mutationFn: async (payload: SaveQuizPayload): Promise<string> => {
      if (!user) throw new Error("Not authenticated");

      const { data: quizRow, error: quizErr } = await (supabase as any)
        .from("quizzes")
        .insert({
          teacher_id: user.id,
          title: payload.title,
          title_ar: payload.title_ar || null,
          lesson_ref: payload.lesson_ref || null,
          book_id: payload.book_id || null,
          subject_id: payload.subject_id || null,
        })
        .select("id")
        .single();
      if (quizErr) throw quizErr;

      const quizId = quizRow.id as string;

      if (payload.questions.length > 0) {
        const rows = payload.questions.map((q, i) => ({
          quiz_id: quizId,
          question_text: q.question_text,
          question_type: q.question_type,
          options_json: q.options_json || null,
          answer: q.answer || null,
          points: q.points || 1,
          sort_order: i,
        }));
        const { error: qErr } = await (supabase as any).from("quiz_questions").insert(rows);
        if (qErr) throw qErr;
      }

      return quizId;
    },
    onSuccess: () => qc.invalidateQueries({ queryKey: ["my_quizzes"] }),
  });
}

/** Update questions for an existing quiz (replace all). */
export function useUpdateQuizQuestions() {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: async ({ quizId, questions }: { quizId: string; questions: QuizQuestion[] }) => {
      // Delete existing
      await (supabase as any).from("quiz_questions").delete().eq("quiz_id", quizId);
      if (questions.length > 0) {
        const rows = questions.map((q, i) => ({
          quiz_id: quizId,
          question_text: q.question_text,
          question_type: q.question_type,
          options_json: q.options_json || null,
          answer: q.answer || null,
          points: q.points || 1,
          sort_order: i,
        }));
        const { error } = await (supabase as any).from("quiz_questions").insert(rows);
        if (error) throw error;
      }
    },
    onSuccess: (_, { quizId }) => qc.invalidateQueries({ queryKey: ["quiz_questions", quizId] }),
  });
}

interface AssignQuizPayload {
  quizId: string;
  classId: string;
  subjectId?: string;
  dueDate?: string;
  title: string;
  titleAr?: string;
  /** Sum of quiz question points — shown on assignments / gradebook */
  maxScore?: number;
  /** When true, this assessment is intended to count toward the grade record */
  countsTowardGrade?: boolean;
  /** "quiz" keeps existing behaviour; "homework" creates a graded homework task with structured questions */
  assignment_type?: "quiz" | "homework";
}

/** Assign a quiz to a class: creates an assignment row + marks quiz assigned + notifies students. */
export function useAssignQuiz() {
  const { user } = useAuth();
  const qc = useQueryClient();

  return useMutation({
    mutationFn: async (payload: AssignQuizPayload) => {
      if (!user) throw new Error("Not authenticated");
      const aType = payload.assignment_type || "quiz";

      // 1. Insert assignment row
      const maxScoreInsert =
        payload.maxScore != null && Number(payload.maxScore) > 0 ? Number(payload.maxScore) : null;
      const { data: assignRow, error: assignErr } = await (supabase as any)
        .from("assignments")
        .insert({
          class_id: payload.classId,
          subject_id: payload.subjectId || null,
          title: payload.title,
          title_ar: payload.titleAr || null,
          due_date: payload.dueDate || null,
          created_by: user.id,
          assignment_type: aType,
          quiz_id: payload.quizId,
          max_score: maxScoreInsert,
          counts_toward_grade: payload.countsTowardGrade !== false,
        })
        .select("id")
        .single();
      if (assignErr) throw assignErr;

      // 2. Mark quiz as assigned + link class
      await (supabase as any)
        .from("quizzes")
        .update({ assigned: true, class_id: payload.classId, due_date: payload.dueDate || null })
        .eq("id", payload.quizId);

      return { assignment_id: assignRow.id as string };
    },
    onSuccess: (_, payload) => {
      qc.invalidateQueries({ queryKey: ["my_quizzes"] });
      qc.invalidateQueries({ queryKey: ["student_assignments"] });
      qc.invalidateQueries({ queryKey: ["class_assignments", payload.classId] });
      toast.success(payload.assignment_type === "homework" ? "Homework assigned — submit & grades like quiz" : "Quiz assigned to class — students notified");
    },
  });
}
